### ISSUE TITLE
Error when reading WAL file

### ISSUE THREAD

**Issue by pmdarrow** [snaga/xlogdump#14]
I receive the following out when running xlogdump against a WAL file from Postgres 8.4.8:

```
$ xlogdump 00000001000000000000005F 

00000001000000000000005F:

invalid record length(expected 94 ~ 24742, actual 90) at 0/5F000020
```

Is this expected behaviour?

**Comment by snaga** [comment]
It's not expected actually. I need to know how to reproduce it in order to determine the issue precisely. Can you share your SQL statements and commands that can reproduce it? Thanks.

**Comment by pmdarrow** [comment]
Here's a WAL file that you can use to reproduce the issue: https://docs.google.com/open?id=0B842HM0q8Cc4ajk2N1RiQkI3MTQ. I do not know the exact SQL statements and commands used to reproduce it, although I suppose I can create a new DB and document my steps. Would that be helpful?

**Comment by snaga** [comment]
Thanks. I just started working on this.

**Comment by snaga** [comment]
I found that the error would come from different xlog record header size, which means xlog header in the WAL file is smaller than xlogdump expected, because the WAL file has been generated on the different architecture, particularly a 32-bit one, and maybe you're using xlogdump built on a 64-bit box.

You will be able to see xlogdump working correctly when you build your xlogdump on a 32-bit box. See follwoing examples for more details.

Currently, xlogdump cannot deal with WAL files generated on the different architecture. So, you need to build xlogdump on the 32-bit architecture when you want to analyze WAL files generated on the 32-bit box. 64-bit as well.

## Example 1: xlogdump built on my 32-bit box does work.

[snaga@devvm03 xlogdump]$ uname -a
Linux devvm03 2.6.18-164.el5 #1 SMP Tue Aug 18 15:51:54 EDT 2009 i686 i686 i386 GNU/Linux
[snaga@devvm03 xlogdump]$ ./xlogdump 00000001000000000000005F | head -10

00000001000000000000005F:

[cur:0/5F000020, xid:313027, rmid:11(Btree), len:62/90, prev:0/5EFFE1F4] insert_leaf: s/d/r:1663/68674/71047 tid 27/26
[cur:0/5F00007C, xid:313027, rmid:11(Btree), len:18/8150, prev:0/5F000020] insert_leaf: s/d/r:1663/68674/71315 tid 16/402
[cur:0/5F00007C, xid:313027, rmid:11(Btree), len:18/8150, prev:0/5F000020] bkpblock[1]: s/d/r:1663/68674/71315 blk:16 hole_off/len:1632/112
[cur:0/5F002068, xid:313026, rmid:1(Transaction), len:20/48, prev:0/5F00007C] commit at 2012-07-06 02:07:06 JST
[cur:0/5F002098, xid:313029, rmid:10(Heap), len:314/342, prev:0/5F002068] update: s/d/r:1663/68674/68772 block 139 off 53 to block 139 off 54
[cur:0/5F0021F0, xid:313029, rmid:11(Btree), len:62/90, prev:0/5F002098] insert_leaf: s/d/r:1663/68674/71047 tid 27/26
[cur:0/5F00224C, xid:313029, rmid:11(Btree), len:34/62, prev:0/5F0021F0] insert_leaf: s/d/r:1663/68674/71315 tid 16/403
[snaga@devvm03 xlogdump]$

## Example 2: xlogdump built on my 64-bit box _does not_ work.

[snaga@devsv02 xlogdump]$ uname -a
Linux devsv02 2.6.18-274.el5 #1 SMP Fri Jul 8 17:36:59 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
[snaga@devsv02 xlogdump]$ ./xlogdump 00000001000000000000005F | head -10

00000001000000000000005F:

invalid record length(expected 94 ~ 24742, actual 90) at 0/5F000020
[snaga@devsv02 xlogdump]$

**Comment by pmdarrow** [comment]
Ah, that makes sense. I will give this a shot. A warning that this might be the problem when the tool detects `invalid record length` errors would very helpful :)

**Comment by pmdarrow** [comment]
Your suggestion worked, thank you!

**Comment by snaga** [comment]
Glad to hear that.
And as you pointed out, I have added some hint and explanation to the error message and README.

https://github.com/snaga/xlogdump/commit/0e4e1a46b124e8779919c661fc3c367e4dcf5e43

Thanks!
